name: Demo Scripts

on:
    push: null
    pull_request: null

jobs:
    demo_scripts:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                actions:
                    - run: composer demo-generate-patch --ansi

                    # config transform to PHP
                    - run: composer demo-transform-config
                    - run: composer demo-transform-config-no-dry

                    # phpstan
                    - run: composer demo-type-coverage

                    # rector
                    - run: composer demo-renamed-class
                    - run: composer demo-renamed-method

                    # rector attributes
                    - run: composer demo-doctrine-attributes

        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.2
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: ${{ matrix.actions.run }}
