name: Rector Tireless Worker

on:
    push: null
    pull_request: null

jobs:
    rector:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
                with:
                    # Must be used to trigger workflow after push
                    token: ${{ secrets.GITHUB_TOKEN }}

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.2
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: vendor/bin/rector process --ansi --config rector-ci.php

            # commit changes, see https://github.com/EndBug/add-and-commit
            -
                uses: EndBug/add-and-commit@v7.5.0
                with:
                    # The arguments for the `git add` command (see the paragraph below for more info)
                    add: .
                    message: "[ci-review] Code rectified by Rector"
                    author_name: "GitHub Action"
                    author_email: "action@github.com"
                env:
                    # to get push access
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
